Quellen hierzu: [url=http://www.arznei-telegramm.de/register/0601001.pdf]arznei-telegramm (a-t) 1/2006, S. 1[/url] und [url=http://www.arznei-telegramm.de/register/0601002.pdf]2[/url] (PDF).
<hr>
Das [url=http://www.arznei-telegramm.de/]arznei-telegramm[/url] wurde für seine sachlich korrekte [url=http://www.adfd.org/forum/viewtopic.php?t=1644]Einschätzung[/url] des Wissensstandes zum Nutzen-Risiko-Verhältnis bei den neueren Antidepressiva unlängst [url=http://www.thieme-connect.de/ejournals/html/psychoneuro/doi/10.1055/s-2005-922235]heftig attackiert[/url]. Die Rolle der Zeitschrift [i][url=http://www.thieme-connect.de/ejournals/toc/psychoneuro/4591]psychoneuro[/url][/i] als propagandistisches "Zentralorgan" der Pharmaindustrie sowie die [url=http://www.adfd.org/forum/viewtopic.php?t=1798]Herstellerverbindungen[/url] der einflussreichen Psychiater, die jetzt den AD-Einsatz so vehement und unsachlich verteidigen, sind aufmerksamen ADFD-Teilnehmern seit langem bekannt.

Das arznei-telegramm lässt sich in seiner aktuellen Ausgabe nun nicht lumpen und wählt ebenfalls deutliche Worte: Bei der massenhaften Verschreibung von Antidepressiva handelt es sich demnach um einen [b]"unkontrollierten Feldversuch"[/b]. Anders ausgedrückt: Die AD-Hersteller führen mit Hilfe der fehlinformierten Ärzte einen Menschenversuch ungeheuren Ausmaßes durch, indem Medikamente, deren tatsächlicher Nutzen noch gar nicht feststeht und deren Gefährdungspotenzial nach wie vor nur unzureichend abgeschätzt werden kann, an Abermillionen von Konsumenten verteilt werden.

Angesichts der vom arznei-telegramm und anderen kritischen Publikationen herangezogenen Daten muss diese Bewertung leider als realistisch gelten. Die von den AD-Verteidigern genannten Kritikpunkte lassen sich relativ leicht entkräften. Das a-t führt dazu u.a. aus, wie eine auf ein möglichst produktfreundliches Resultat orientierte Studienplanung und -auswertung den gemessenen Effekt eines Antidepressivums vielfach größer erscheinen lässt, als er tatsächlich ist.

Auf die bereits mehrfach geäußerte substanzielle Kritik des a-t am Design vieler wichtiger AD-Studien, wonach die Präparate nicht wirklich gegen Placebo [i]verblindet[/i] werden können, weil die Störwirkungen (Mundtrockenheit!) so charakteristisch sind und deren Ausbleiben von den Probanden eindeutig bemerkt wird, ging die AD-Fraktion in ihrer Attacke gar nicht erst ein. Dieselbe Ignoranz zeigen die AD-[i]Vertreter[/i] bezüglich des schwerwiegendsten Arguments aus der a-t-Bewertung vom Mai 2005: Wenn nämlich standardmäßig 5-10 Studien angesetzt werden, wobei letztlich nur eine zu positiven Ergebnissen kommen muss und die restlichen Resultate im Panzerschrank verschwinden, dann lässt sich mittels entsprechender "kreativer" Datenauswertung in der Fachöffentlichkeit - und zum Zweck der behördlichen Zulassung! - der gewünschte Eindruck einer nennenswerten Wirksamkeit erwecken. Die in den vergangenen Jahren publizierten positiven AD-Studienbefunde lassen sich so ohne weiteres erklären - zumal anzunehmen ist, dass bei allen durch die Hersteller bezahlten Studien, sowohl bei den "verschwundenen" als auch bei den veröffentlichten, von vornherein mit den oben erwähnten Designtricks gearbeitet wurde.

Anstelle plausibler Gegenargumente lieferten die Antidepressiva-Apostel Beschimpfungen und sogar eine faustdicke Lüge - der aus Sicht der Pharmaindustrie zum Feind Nr. 1 avancierte Prof. Sawicki ist schon lange nicht mehr beim arznei-telegramm tätig, wie von den Angreifern behauptet wurde. Seit Mitte 2004 leitet er vielmehr das Institut für Qualität und Wirtschaftlichkeit im Gesundheitswesen (IQWiG). Zu dessen Aufgaben gehört es, wie sein Name schon sagt, mittels wissenschaftlicher Einschätzungen für höchste Qualität der medizischen Versorgung bei bestmöglicher Effizienz zu sorgen.

Welche Meinungen über die reale Wirksamkeit und die gesundheitsökonomische Effizienz der neueren Antidepressiva auf seiten ihrer Befürworter wirklich bestehen, könnte ein informierter Beobachter aus diesem Verhalten schlussfolgern. Das a-t hält sich in dieser Hinsicht bemerkenswert zurück und überlässt die Wertung den Lesern.

<hr>
für das ADFD:
[i]Philipp-R. Schulz[/i]