# Need more hooks? see https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["--safe", "--exclude docs/*", "--exclude adfd/site/semantic/*", "--exclude adfd/site/static/*"]
        language_version: python3.6

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
      -   id: flake8
          additional_dependencies: ["flake8-bugbear == 19.3.0"]
          language_version: python3.8

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
