Empfehlung von Chrissy: [url=http://www.amazon.de/Nur-bei-Bedarf-Gro%C3%9Fdruck-Abh%C3%A4ngigkeitsfalle/dp/3845915374]Nur bei Bedarf: Die Abhängigkeitsfalle[/url]

[quote="Amazon.de"]
Medikamentenabhängigkeit und Angstzustände belasten das private und berufliche Leben extrem. Nur wenige Betroffene sind bereit, sich zu outen. Doch viele suchen Hilfe. Ben Diaz weiß, wovon er spricht. Er war dreizehn Jahre unbewusst medikamentenabhängig. In diesem Buch stellt er die Symptome eindringlich dar und zeigt auf, welche Schritte im Vorfeld erforderlich sind, um einen Entzug erfolgreich durchzustehen. Dabei hat er ein ganz besonderes Augenmerk auf die notwendigen inneren Veränderungen. Denn nur durch einen ungeschönten Blick nach innen ist es möglich, Blockaden zu erkennen, einen neuen Standpunkt einzunehmen, und frei von Vorurteilen und falschen Wahrheiten in eine neue Lebensphase zu starten. Dieser Erfahrungsbericht hilft nicht nur mit konkreten Tipps bei der Überwindung von Abhängigkeit und Angst. Er zeigt darüber hinaus in Diagrammen einen detaillierten Entzugsverlauf (Medikation, körperliche und psychische Symptome) über den Zeitraum eines Jahres hinweg.

[b]Über den Autor und weitere Mitwirkende[/b]
Ben Diaz (Pseudonym), geb. 1965, ist gelernter Energie- und Anlagenelektroniker. Er arbeitete über viele Jahre in einem internationalen Konzern als Projektingenieur, Projektleiter, Konzern-Betriebsratsvorsitzender, Betriebsratsvorsitzender und Teamleiter im technischen Außendienst. Heute hilft er als Coach und psychologischer Berater engagierten Menschen und Paaren Krisen zu überwinden und ein neues individuelles Lebenskonzept zu erarbeiten. Seine Freizeit gehört dem Fußball. Aktuell trainiert er eine aktive Mannschaft der A-Klasse. Er ist verheiratet, hat zwei Kinder und lebt in der Nähe von Mainz.[/quote]

Diesen Text hat Ben mir noch dazu geschickt - danke Ben :)

[quote="Ben"][b]Warum ich mit meiner Geschichte an die Öffentlichkeit gehe [/b]

Wieso mache ich das? Diese Frage stellte ich mir während des Buchprojektes immer wieder. Weshalb schreibe ich meine Geschichte auf und riskiere damit, meine persönlichen Probleme, Krisen und Schwächen schonungslos an die Öffentlichkeit zu bringen? Und gab mir auch gleich die Antwort: Weil es im Internet und in den Fachbuchhandlungen zwar Informationen über Medikamentenabhängigkeit und deren Bewältigung gibt, aber zu wenige. Und wenn dann doch einmal ein informatives Buch zu finden ist, wird diese Thematik meist nur lückenhaft behandelt. Ich habe selbst erlebt, wie schwer es ist, Erfahrungsberichte zu bekommen. Nur wenige Betroffene sind bereit, sich zu outen. Fast scheint es, als sei medikamentenabhängig zu sein oder einem Suchtmittel zu erliegen, eine Seuche, der man schleunigst aus dem Weg gehen sollte. Warum nimmt der oder die denn auch so viele Tabletten? Warum trinkt der so oft über den Durst? Warum raucht die unentwegt Zigaretten? 

Kein Abhängiger ist morgens aufgestanden und hat gesagt: „Ich werde dann mal süchtig!“ Doch ein Mensch wird schneller abhängig als er denkt. Wobei unsere Gesellschaft zahlreiche mehr oder weniger harmlose Drogen durch Akzeptanz unterstützt, zum Beispiel Alkohol und Nikotin. Hinzu kommen Konflikte wie Arbeitslosigkeit oder finanzielle, private oder berufliche Probleme, die eine Abhängigkeit fördern können. 

Ich stehe zu meiner Vergangenheit und weiß, ICH BIN NICHT ALLEINE. Europaweit gibt es zig Millionen Menschen, die einer Abhängigkeit, egal welcher Art, verfallen sind, unter psychischen Störungen leiden oder gar unter beidem: Spielsucht, Internetsucht, Sexsucht, Magersucht, Medikamenten- sowie Drogenabhängigkeit, Bulimie in Verbindung mit der Abhängigkeit von Abführmitteln, Schlafstörungen kombiniert Schlafmitteln … Alleine 9,5 Mio. Menschen in Deutschland konsumieren Alkohol in gesundheitlich riskanter Form. In diesem Buch zeige ich den konkreten Verlauf in die (unbewusste) Abhängigkeit, aber auch wieder heraus. Denn wie ich aus Internetforen weiß, suchen zahlreiche Betroffene Hilfe. Sie wünschen sich Informationen über den Verlauf eines Entzugs, Symptome, Dauer, psychische und physische Beeinträchtigungen sowie Tipps, um die Belastungen besser durchzustehen. Und genau hierin liegt meine Motivation. Obwohl … das wäre zu uneigennützig. Denn es ist ein Bonus für mich, dieses Buch zu schreiben, da mir die schriftliche Aufarbeitung hilft, diese für mich sehr schlimme Zeit zu verarbeiten. Auch das bringt mich auf meinem neuen Weg ein Stück voran.[/quote]