Wenn ich mehr Geld hätte, würde ich auch eine gute, auf Medizinrecht spezalisierte Anwaltskanzlei auf die Herstellerfirmen von Venlafaxinprodukten ansetzen und die mit einer Sammelklage konfrontieren. Wenn man sich ansieht, wie viele allein hier im Forum damit zu kämpfen haben...

Das wär mal was  :x  :sports:  :haha:  :twisted: