[b][u]Hintergründe:[/u] zum verschleppten Zulassungsverfahren[/b]

Die Zulassungsentscheidung der EMEA zum Agomelatin-Präparat VALDOXAN verzögert sich weiter. [url=http://www.neurotransmitter.net/newdrugs.html]Mitte 2008[/url] ist lange vorbei, und seit Jahresanfang haben sich die Prognosen der üblichen Werbeblättchen und von Servier selbst über [url=http://www.thieme-connect.com/ejournals/html/psychoneuro/doi/10.1055/s-2008-1079281]Herbst 2008[/url] schon auf [url=http://www.presseportal.de/story.htx?nr=1209301]Ende 2008[/url] geändert, was einen Markteintritt etwa Anfang 2009 bedeuten würde.

[url=http://www.adisinsight.com/Articles/PE1-08-04e.pdf]Analysten[/url] sehen die aktuellen Zulassungschancen für Agomelatin bei 30 Prozent und prognostizieren einen relativ geringen Spitzenumsatz von 200 Mio $ jährlich. Angesichts solcher Aussichten dürfte es für Servier äußerst schwer werden, im Falle einer erneuten Ablehnung von VALDOXAN eine wirtschaftliche Rechtfertigung für einen nochmaligen Anlauf zu finden. Ein ähnlicher Kraftakt, wie ihn Eli Lilly mit [i]Duloxetin[/i] hingelegt hat, das trotz jahrelanger Rückschläge und Skandale dank finanzintensivem Marketing mittlerweile Milliarden einfährt, ist der vergleichsweise kleinen Firma Servier kaum zuzutrauen.

Ein prinzipieller Vorteil gegenüber dem kürzlich von der EMEA [url=http://www.reuters.com/article/rbssHealthcareNews/idUSL0268741320080602]zurückgewiesenen[/url] zweiten Melatonin-Analogon [i]Ramelteon[/i] könnte Servier noch nutzen: Agomelatin wird als [i]Antidepressivum[/i] bezeichnet und nicht als Schlafmittel, obwohl die meisten Studien die Wirkung auf die Schlafqualität hervorheben. Die Wirkung von Antidepressiva lässt sich bekanntlich kaum von der Placebowirkung [url=http://medicine.plosjournals.org/perlserv/?request=get-document&doi=10.1371%2Fjournal.pmed.0050045]unterscheiden[/url]. Somit hat Agomelatin immer noch eine grundsätzliche Chance auf Zulassung, auch wenn die vorgezeigten Daten eher eine Placebowirkung belegen. Die Anforderungen der Zulassungsbehörden an künftige Antidepressiva sind derart bescheiden, dass auch Agomelatin durchkommen könnte, obwohl es in 4 von 6 Phase-III-Studien versagte. Die gepoolte Auswertung aller Studien ergab laut EMEA einen Unterschied zu Placebo von 1,55 HAM-D-Punkten, was [i][b]klinisch [/b]definitiv [b]irrelevant[/b][/i] ist. Die antidepressive Effektstärke der Substanz liegt bei [color=#800000]höchstens [b]0,18[/b] SMD[/color] und damit klar unter der von SSRI und anderen gängigen Antidepressiva (eigene Berechnung, Methodik nach [url=http://content.nejm.org/cgi/content/full/358/3/252]Turner et al[/url]).

[b]Preisgekröntes Marketing[/b]

Gerade wurden die diesjährigen Nobelpreisträger benannt, da geben Servier und die [i]World Psychiatric Association[/i] (WPA) ein Kick-back-Geschäft der ganz besonderen Art bekannt: die Verleihung des [url=http://www.servier.com/Corporate/NewsView.aspx?idx=400]Jean-Delay-Preises an Prof. H.-J. Möller[/url]. Der nach dem ersten WPA-Präsidenten benannte Preis wird kurzerhand zum "Nobelpreis für Psychiatrie" erklärt, ist aber vergleichsweise mickrig dotiert mit 40.000€. Das liegt vermutlich daran, dass der Stifter - die Firma Servier höchstselbst - keine so weltbewegenden Erfindungen wie Nobel's [i]Dynamit[/i] vorzuweisen hat. Ob die Marketingaktivitäten von Prof. Möller für Servier's [i]Agomelatin[/i], über dessen Zulassung die EMEA im gleichen Zeitraum zu befinden hat, eine Rolle bei der Auszeichnung spielten, bleibt im Dunklen. Die Verleihung des Preises brächte im Falle einer Markteinführung von VALDOXAN beiden Seiten finanzielle Vorteile - ein genialer Marketingschachzug, wenn es denn dazu kommt.

Möller hat in seiner [url=http://www.servier.com/App_Images/news/download/Delay2008.pdf]Dankesrede[/url] Agomelatin nicht direkt erwähnt, nur einige [url=http://www.ncbi.nlm.nih.gov/pubmed/17690597]Werbeartikel[/url] zitiert. Selbstverständlich hat er nochmals Kirsch et al. abgestraft, und bemerkenswerterweise [url=http://www.ncbi.nlm.nih.gov/pubmed/17854243]Stassen & Angst et al.[/url] mit ihrer [i]resilience[/i]-Theorie erwähnt. Zur [url=http://www.adfd.org/wissen/Wirksamkeit_von_Antidepressiva]Erinnerung[/url]: Diese Gruppe hatte festgestellt, dass es keinen Unterschied zwischen Verum- und Placebo-Response in Antidepressiva-Studien gibt.

Das Annehmen von Pharmapreisen ist im Übrigen gängig in den Kreisen der meinungsführenden Psychiater, von [url=http://www.holsboer.de/biographie.html]Holsboer[/url] bis [url=http://www.lilly-pharma.de/presse/unternehmensnachrichten/archiv/zahlen-und-fakten/lilly-quality-of-life-preis-2007-verliehen.html]Naber[/url]. Das Praktische daran: Man kriegt richtig Geld, muss dann aber nicht unbedingt einen Interessenkonflikt deklarieren, denn es ist eine Jury zwischengeschaltet.

[b]Gut geschmiert ist halb gewonnen[/b]

Die Zulassung durch die EMEA hängt von der Empfehlung des Expertengremiums CHMP ab. Das ist für alle Humanarzneimittel zuständig, ob nun für Bluthochdruckmittel oder Osteoporosepräparate oder eben Psychopharmaka. Für die einzelnen Fachgebiete holt es sich dann Spezialisten von außerhalb, im Falle der ZNS-Medikamente ist das eine [url=http://www.emea.europa.eu/htms/general/contacts/CHMP/CHMP_SAG-CNS.html]SAG-CNS[/url] genannte "Beratergruppe". Aufgabe der SAG-CNS ist die Abgabe "unabhängiger Empfehlungen" im Zusammenhang mit Zulassungen ([i]"to provide independent recommendations on scientific/technical matters relating to products under evaluation (pre- or post-authorisation) by the CHMP"[/i]). Laut deren [url=http://www.emea.europa.eu/pdfs/human/sag/21152705en.pdf]Regeln[/url] sind Firmenbeziehungen unerwünscht und müssten eigentlich angegeben werden. Die Website der EMEA scheint aber in dieser Hinsicht nicht up-to-date zu sein:

Mitglieder der SAG-CNS sind unter anderem
[list][*] Serge Bakchine[list][*][url=http://agmed.sante.gouv.fr/pdf/5/dpi2007.pdf]deklariert[/url] Zuwendungen von Servier[/list][/*:m]
[*] Timothy G. Dinan[list][*]hat [url=http://www.cinp.org/]via CINP[/url] mit Servier [url=http://www.irishpsychiatry.com/WEB%20Events%20Register%2027-02-07.xls]zusammengearbeitet[/url][/list][/*:m]
[*] Jean Pierre Lépine (Vice-Chair)
[list][*]Dr Jean-Pierre Lepine has [url=http://www3.interscience.wiley.com/journal/121388483/abstract]educational support from Servier[/url][/list][/*:m]
[*] sowie Hans-Jürgen Möller[list][*]...has served as consultant or adviser to Servier and Wyeth, and has received grant/research support from Eisai, Merck, Novartis, Sanofi Aventis, Servier and Wyeth [url=http://www.ncbi.nlm.nih.gov/pubmed/18787661](usw.)[/url][/list][/*:m][/list:u]
Unter diesen Umständen sind die Chancen für Agomelatin (VALDOXAN) wohl deutlich höher einzuschätzen. Servier hat aus der Niederlage 2006 offenbar gelernt. [b][u]Prognose:[/u] 60% Zulassungswahrscheinlichkeit.[/b]

# # # # # #

[i][b]SOFORT-UPDATE[/b][/i] - 27.10.2008
Nun ist es amtlich: [i]Agomelatin [/i](VALDOXAN) wird im Jahr 2008 in keiner Weise mehr erhältlich werden. Das CHMP hat das Thema in [url=http://www.emea.europa.eu/pdfs/human/press/pr/55020608en.pdf]seiner Oktober-Sitzung[/url] wieder nicht behandelt. Selbst wenn Ende November zur nächsten Beratung eine positive Entscheidung fallen sollte, wäre mit einem Markteintritt wegen des nötigen Prozederes (EU-Kommissionserlass, örtliche Umsetzung, Inverkehrbringen) erst etwa im Februar 2009 zu rechnen.

# # # # # #
:!: [size=90][color=#808080]Im Augenblick lohnen weitere Ausführungen nicht, da die Zulassung ungewiss ist. Wir werden als einzige unabhängige und kritische Quelle im deutschen Internet dranbleiben und weiter das nötige Kontrastprogramm zu der ausufernden Jubelpropaganda im Netz bieten.[/color][/size]