Das erinnert mich an das TeenScreen Programm in den USA. 
(siehe Doku unter TV, Artikel usw.)

Test ablegen, zum Arzt gehen, Psychopharmaka schlucken. Erst die Teenager und dann die Kinder...
Und alle meinen es ja nur gut...