[url=http://www.heise.de/tp/r4/artikel/19/19193/1.html]Quelle: Telepolis[/url]
[quote][b]Antidepressiva unter Kritik[/b]
[i]Stefanie Schneider - 11.01.2005[/i]

[b]Erneut steht der US-Pharmakonzern Eli Lilly in der Kritik, Risiken und Nebenwirkungen seines Verkaufsschlagers Prozac verschwiegen zu haben[/b]

[i]Wie das [url=http://www.aerzteblatt.de/v4/news/news.asp?id=18694]deutsche Ärzteblatt berichtete[/url] ist der Krankenstand 2004 auf ein historisches Tief gesunken, wobei jedoch psychische Erkrankungen immer häufiger zu Fehlzeiten am Arbeitsplatz führten. Sie seien mittlerweile die vierthäufigste Ursache für Fehlzeiten in den Betrieben. Antidepressiva jedoch, vielfach als Allheilmittel gegen psychische Erkrankungen gepriesen, werden zunehmend kritisiert und geraten mit Negativschlagzeilen ins Licht der Öffentlichkeit.[/i]

Das [url=http://bmj.bmjjournals.com/cgi/content/full/330/7481/7?ehom]British Medical Journal[/url] berichtet ihm sei im vergangenen Monat anonym vertrauliches Material zugespielt worden, welches einen kausalen Zusammenhang zwischen der Patienten-Medikation mit selektiven Serotonin-Wiederaufnahmehemmern (SRRI, z. B. Prozac) und erhöhtem Hang zu Aggressionen, Gewalt und Suizid belege. Das Material wurde der US-Behörde für Arzneimittelsicherheit (FDA) zur Prüfung übergeben.
Bei den entsprechenden Dokumenten handele es sich anscheinend um interne Memos, Produktstudien und Bewertungspapiere des Pharmariesen Eli Lilly aus dem Jahr 1988, aus welchen klar hervorgeht, dass der Firma bekannt war, dass die Einnahme von Prozac zu einer signifikanten Zunahme von nervösen "Erregungszuständen" führen könne, was diese bisher stets bestritten hatte. Klinischen Tests zufolge sind bei 38% der damaligen Prozac-Probanden derartige Symptome aufgetreten.
Pikanterweise waren eben diese Dokumente während des Wesbecker-Prozesses im Jahre 1994 verschwunden, wo sie als wichtige Beweismittel hatten dienen sollen. Der Journalist Joseph Wesbecker war 1989 mit einer 47er Magnum Amok gelaufen und hatte dabei 8 Menschen erschossen und ein Dutzend verletzt. Eine lange Leidensgeschichte von Depressionen und Angstzuständen fand mit dem Suizid ein Ende. Einen Monat vorher hatte er auf Empfehlung seines Arztes begonnen Prozac zu nehmen.
Das Unternehmen wurde zwar mit 9 zu 3 Geschworenenstimmen freigesprochen; später kam jedoch ans Licht, dass die Firma die Kläger, Angehörige der Opfer, bereits vorher in einem geheimen Deal großzügig abgefunden hatte. Vermutlich ebenso wie in etwa 200 anderen Fällen, die teilweise bereits vor der Verhandlung vor Gericht auf ähnliche Weise "beigelegt" wurden ([url=http://www.heise.de/tp/r4/artikel/8/8397/1.html]Leere Couch, volle Pillendose[/url]).

[b]Nicht nur Prozac ist betroffen[/b]
Wie die Dokumente (bzw. deren damaliges Verschwinden) belegen, hat Eli Lilly nicht nur den möglichen Zusammenhang zwischen der Prozac-Einnahme und dem Amoklauf von Wesbecker erkannt und vertuscht, sondern auch weiterhin alles darangesetzt, das Medikament ohne weitere Überprüfung in den Markt zu schwemmen. Besser noch, konnte sich die Firma doch nun mit dem Prädikat "Sicherheit und Wirksamkeit gerichtlich bestätigt" schmücken und diesen sogenannten Sieg somit werbetechnisch reichlich ausschlachten.
Die Quasi-Absolution von höchster Stelle könnte einen nicht unerheblichen Teil dazu beigetragen haben, Prozac zu einem der "beliebtesten" Medikamente der USA zu machen. Doch das Barometer der Gunst scheint zu sinken. So hat die US-Behörde erst vor kurzem eine Warnung ausgesprochen der zufolge Antidepressiva Erregungszustände wie Unruhe, Panikanfälle, Schlaflosigkeit und Aggressivität hervorrufen können. Dies wurde von Joseph Glenmullen, einem Psychiater an der Universität Harvard, als wenig überraschend bezeichnet, da es hinsichtlich seiner Wirkung auf den Neurotransmitter Serotonin der Wirkung von Kokain sehr ähnlich sei. Glenmullen, der bereits seit Jahren vor den Folgen unkontrollierter und langanhaltender Prozac-Medikation warnt, hat in seinem Buch "Prozac Backlash" unterschiedliche Fälle zusammen getragen und die unverantwortliche Markttaktik von Eli Lilly angeprangert.
Aber auch anderen Firmen weht seit geraumer Zeit ein rauer Wind ins Gesicht. So hat der Staat New York Mitte letzten Jahres in einem dem Wesbecker-Amoklauf ähnlich gelagerten Fall Anklage gegen den Pharmamulti GlaxoSmithKline erhoben ([url=http://www.heise.de/tp/r4/artikel/17/17812/1.html]Selbstmord aus der Pillendose?[/url]), der u. a. das Antidepressivum Paxil vertreibt.
Vorausgegangen waren Fälle von jugendlichem Suizid in England, woraufhin die UK Medicines and Healthcare Products Regulatory Agency (MHRA) im April 2003 ein Expertengremium eingesetzt hatte, das Sicherheit und Effizienz dieser Medikamentengruppe überprüfen sollte. Nach [url=http://www.thelancet.de/artikel/715067]abschließender Neubewertung[/url] wurden in England und Kanada alle Produkte bis auf Prozac (weil die entsprechenden Daten nicht vorlagen?) für Jugendliche unter 18 Jahren verboten.
Der entscheidende Kritikpunkt in diesem Themenkomplex ist ohne Zweifel, die mangelnde Transparenz mit der die betroffenen Pharmafirmen agieren. Solange immer [url=http://www.prozactruth.com/]neue Fälle[/url] ans Licht kommen, in denen Pharmafirmen versuchen Studien zu unterdrücken oder gleich ganz verschwinden lassen, Kritiker mit großzügigen Zuwendungen auf ihre Seite ziehen oder zuständige Institutionen unter Druck setzen, dürften die Rufe nach einer verpflichtenden Offenlegung aller Forschungsergebnisse durch die Pharmaindustrie so schnell nicht mehr verstummen.
Derartige Schlagzeilen lassen aber auch immer wieder aufs Neue Diskussionen über den generellen Nutzen der Behandlung von psychischen Erkrankungen mit Medikamenten entbrennen. Häufig wird auf die [url=http://observer.guardian.co.uk/focus/story/0,6903,1194292,00.html]Übermedikation[/url] und im schlimmsten Falle auf eine drohende [url=http://www.wienerzeitung.at/frameless/wissen.htm?ID=M13&Menu=219501]Zwangsmedikation[/url] schon im Kindesalter hingewiesen.

[b]Allgemeinplätze und wenig Sachkenntnis[/b]
Eine Buchveröffentlichung von Jörg Blech vom Februar letzten Jahres soll aufzeigen, wie Pharmaindustrie und Ärzteschaft sich durch das Erfinden von Krankheiten neue Zielgruppen erschließen und weitere Marktanteile sichern. Wie aus einstmals gesunden und putzmunteren Leuten, arme Kranke gemacht werden möchte sein Buch "Die Krankheitserfinder" belegen. Dabei spart der Autor auch die psychischen Erkrankungen nicht aus, da dieser Bereich von jeher unter Generalverdacht stand, besonders viele Simulanten hervorzubringen.

<div class="liste">[b]Kapitel 5: Wahnsinn wird normal[/b]
Wie unterscheidet man einen Verrückten von einem Gesunden? David Rosenhan, Psychologe an der Stanford University in Kalifornien, hat es 1968 ausprobiert, im Selbstversuch....
Er ließ sich Bartstoppeln sprießen und trug dreckige Kleidung. Dann vereinbarte er unter falschem Namen einen Termin in einer psychiatrischen Anstalt ...
In der Aufnahmestation berichtete Rosenhan den Ärzten von Stimmen, die er gehört haben wollte. Diese seien kaum zu verstehen gewesen, hätten aber leer, dumpf und hohl geklungen ... Rosenhan gab diese Symptome vor, weil in der ganzen Literatur keine einzige Psychose beschrieben wird, die zu ihnen passte.</div>
So wird gerade auf dem hochkomplexen und hochsensiblem Gebiet der psychischen Erkrankungen mit viel plakativen Allgemeinplätzen und mit wenig fundierter Sachkenntnis gearbeitet, wodurch die Zusammenhänge simplifiziert und verzerrt werden. Das schadet in erster Linie den Betroffenen, die nicht nur verunsichert, sondern deren Leiden durch Veröffentlichungen ähnlicher Art bagatellisiert werden und dadurch in der öffentlichen Meinung auf weniger Akzeptanz und Verständnis stoßen als ohnehin schon.
Von einem unkontrollierten und unsachgemäßen Gebrauch von Antidepressiva ist sicherlich abzuraten. Auch und gerade, da die medizinischen Risiken und Langzeitfolgen bislang weder abzuschätzen noch erforscht sind. Auch wäre bessere Kenntnis von Ursachen und Symptomatik von psychischen Erkrankungen seitens der behandelnden Ärzte von Nöten, um psychische Erkrankungen möglichst genau abzugrenzen. Wird bei Trauer, Arbeitsplatzverlust oder ähnlichen Unwägbarkeiten des Lebens sofort der Rezeptblock gezückt, bzw. zur Tablette gegriffen, ist eine "Übermedikation" der Bevölkerung nicht weiter verwunderlich.
Menschen allerdings, die unter dem Leidensdruck stehen, den eine schwere Depression verursacht, sind bisweilen auf die "Auszeit" die ihnen eine zeitlich begrenzte Einnahme von Antidepressiva bringt unbedingt angewiesen, da sie zu bestimmten Zeiten ansonsten psychisch und physisch nicht mehr in der Lage wären am Leben teilzunehmen.
Daher ist es geboten, trotz aggressiver Marktmacht der Pharmaindustrie, die Diskussion ein stückweit zu versachlichen und die Happy Pills nicht in Grund und Boden zu verdammen, die bislang nicht nur Leben gekostet, sondern auch erhalten haben. Auf der anderen Seite sollte jedoch auch nicht unerwähnt bleiben, dass Antidepressiva psychische Krankheiten nicht heilen. Sie verschaffen lediglich ein stückweit lebenswertes Leben auf Zeit. Wer nicht ein Leben lang von Medikamenten abhängig sein will, wird um therapeutische Hilfe ohnehin nicht herum kommen. [/quote]