... und das (In)Kompetenznetz Depression ignoriert weiterhin die sich immer weiter häufenden Hinweise auf die verantwortungslose Massenverschreibung von SSRI für alle möglichen und unmöglichen Symptomkonstellationen ...

Echt Peinlich ...
Oliver