Oh je... lieder scheint dieser Link nicht zu funktionieren...
daher einfach die Seite des S.D. Forums...
Vielleicht klappt das besser??
Sorry...

[url]http://www.ht-mb.de/forum/showthread.php?1234669-Mirtazapin-und-Cortisol-Hypercortisolismus[/url]

Lb Grüße
Siggi