[b]Warum soll ich langsam absetzen? Warum kann ich nicht einfach das Medikament weglassen?[/b]

Entzugssymptome können (auch zeitverzögert) nach Beendigung der Einnahme auftreten und Wochen, Monate oder vereinzelt leider auch Jahre anhalten. [b]Manche Menschen können die Psychopharmakaeinnahme ohne größere Probleme beenden, schwere und verzögerte Entzugssyndrome können aber auch entstehen, und man weiß nie, wen es trifft.[/b] Man weiß es vorher einfach nicht. Langsames Absetzen über einen längeren Zeitraum ist der (bisher) einzig bekannte Weg das Risiko schwerer Entzugssyndrome zu verringern. Niemand sollte die Unversehrheit des Nervensystems riskieren - [b]nach Möglichkeit (außer bei schwerwiegenden Nebenwirkungen) sollte man die Behandlung mit Psychopharmaka nicht abrupt abbrechen, in dem man von heute auf morgen die gewohnte Dosis nicht mehr einnimmt[/b].

Das Nervensystem (und darüber in kaskadischen Wechselwirkungen alle Körpersysteme) wurde körperlich abhängig von der Medikation.
Psychopharmaka beeinflussen dadurch den ganzen Körper, alle Systeme: Nervensystem, Hormonsystem, Kreislauf, Muskelsystem, Verdauungssystem, Atmungssystem, Immunsystem, Harnsystem, Fortpflanzung, das Skelett und die inneren Organe: Herz, Leber, Gallenblase, Nieren, Gehirn, Lymphe, Milz, Magen, Darm. Es kommt ggf. zu Bluthochdruck, zu einer übermäßigen Konzentration von Cortisol im Blut unter anderem mit erhöhtem Blutzuckerspiegel. 

Langsames Absetzen ermöglicht es Deinem Nervensystem zu seinem ursprünglichen homöostatischen Gleichgewicht wiederzufinden. Eine 10%-Reduktion alle 3-4 Wochen (Surviving Antidepressants) bzw. alle 4-6 Wochen (ADFD) - bzw. individuell angepasste Dosisschritte und Absetzzeiträume je nach Absetzsymptomatiken - sind ein Ansatz zur Schadensbegrenzung.

[i]Quelle und Copyright [url=http://survivingantidepressants.org/index.php?/topic/300-important-topics-in-the-tapering-forum-and-faq/?p=2864]Altostrata[/url], übersetzt, angepasst und ergänzt vom Team des ADFD[/i]