[b]Was sind typische Absetz-/Entzugssymptome?[/b]

Wer neuroaktive Medikamente absetzt, dessen Nervensystem muss in eine normale Funktionsfähigkeit ohne weitere Beeinflussung durch von außen zugeführte Substanzen zurückfinden. [b]Während es sich anpasst, kann man Absetzprobleme/Entzugssymptome erleben. [/b]Das vegetative Nervensystem (als Teil des zentralen Nervensystems) kontrolliert die "automatischen" Funktionen des Körpers und es ist von den Veränderungen beim Absetzen betroffen. Das ist auch der Grund warum Absetzsymptome so variabel sind. 

EDIT: [b]Über das vegetative Nervensystem werden biologische, automatisch ablaufende innerliche Vorgänge angepasst und reguliert, die vom Menschen willentlich nicht direkt, sondern allenfalls indirekt beeinflusst werden können. [/b]Über das vegetative Nervensystem werden zur Aufrechterhaltung des inneren Gleichgewichts (Homöostase) die lebenswichtigen Funktionen (Vitalfunktionen) wie Herzschlag, Atmung, Verdauung und Stoffwechsel kontrolliert und gesteuert. Auch andere Organe oder Organsysteme werden vom vegetativen Nervensystem beeinflusst, so beispielsweise die Sexualorgane, Endokrine Drüsen (Hormone), Exokrine Drüsen (wie z.B. Schweißdrüsen), das Blutgefäßsystem (Blutdruck) oder die inneren Augenmuskeln (Pupillenreaktion). [url]https://de.wikipedia.org/wiki/Vegetatives_Nervensystem[/url]

Hinweis ADFD: [b]Das, was in den Beipackzetteln der Medikamente "Nebenwirkungen" genannt wird und in den Fachinformationen für Ärzte (kann man einfach über Suchmaschinen finden) "Erkrankungen" heißt, das sind alles Punkte, die zeigen, wie sich Medikament in allen Körpersystemen auswirken [/b]- und natürlich umfassen diese Aufstellungen nicht alle potentiell möglichen Nebenwirkungen und individuell können auch noch ganz andere unerwünschte Arzneimittelwirkungen auch beim Absetzen auftreten als die dort aufgeführten. [b]In den Hinweisen zu dem Medikamenten sind übrigens auch oft "psychiatrische Erkrankungen" als Nebenwirkungen aufgeführt.[/b] Psychische Auswirkungen können sich auch beim Absetzen zeigen.

Übersichten zu möglichen [b]körperlichen, kognitiven oder psychischen[/b] Entzugsymptomen gibt es unter folgenden Links:
[url]http://www.antidepressiva-absetzen.de/Stufe_3.html[/url]
[url]http://adfd.org/austausch/viewtopic.php?p=104330#p104330[/url] (Fachartikel von Dr. Giovanni Fava et.al.)

[i]Quelle und Copyright [url=http://survivingantidepressants.org/index.php?/topic/300-important-topics-in-the-tapering-forum-and-faq/?p=2866]Altostrata[/url], übersetzt, angepasst und ergänzt vom Team des ADFD[/i]