Liebe Teilnehmer.

Um unnötige Missverständnisse und Auseinandersetzungen zu vermeiden, versuchen wir hier mal auf den Punkt bringen, worum es in diesem Forum geht und auch worum es hier [b]nicht[/b] geht.

Wir haben dieses Forum 2003 ins Leben gerufen, weil es damals im deutschsprachigen Raum noch keine Plattform gab, in der man sich unbehelligt über gefährliche Nebenwirkungen und Abhängigkeit von [url=http://www.adfd.org/forum/viewtopic.php?p=5237#5237]"modernen" Antidepressiva"[/url] austauschen konnte. In anderen Foren war und ist dies auch oft heute noch aus verschiedenen Gründen nicht möglich. [b]Dies ist die zentrale Aufgabe dieses Forums.[/b]

Die aktuell verbreitete Lehrmeinung bzw. ausgeübte Praxis ist, dass bei vielen psychischen Störungen die Behandlung mit Medikamenten die erste Wahl ist. Wir teilen diese Meinung [b]nicht[/b]. Nach unserem derzeitigen Wissensstand ist die medikamentöse Behandlung von psychischen Störungen in vielen Fällen nicht die beste Wahl. Gerade bei den sogenannten "modernen" Antidepressiva wird der Nutzen oft überschätzt und die Risiken unterschätzt. [b]Ausnahmslos alle Psychopharmaka[/b] bekämpfen nur Symptome und nicht die Ursache der Problematik - oder falls sie es doch täten, kann man das mit heutigen Methoden zumindest nicht belegen. Wir halten unsere [b]Meinungen[/b] allerdings nicht für unumstößliche Wahrheiten - sie haben aber ihre Berechtigung und sollten auch [url=http://www.adfd.org/forum/viewforum.php?f=15]öffentlich diskutiert[/url] und nicht sofort [url=http://www.adfd.org/forum/viewtopic.php?t=964]pauschal diskreditiert[/url] werden. Es ist jeder herzlich eingeladen, in der Kategorie [url=http://www.adfd.org/forum/viewforum.php?f=6]Hintergrundinformationen[/url] mehr über das Thema zu lernen und in der Kategorie [url=http://www.adfd.org/forum/viewforum.php?f=15]Diskussion[/url] die bisherigen Threads zum Thema durchzulesen und die eigene Sicht der Dinge einzubringen. Wegen der emotionalen Aufladung dieser Diskussion möchten wir allerdings mit Nachdruck darauf hinweisen, dass jeder Teilnehmer hier ganz besonders auf die [url=http://de.wikipedia.org/wiki/Netiquette]Netiquette[/url] und unsere [url=http://www.adfd.org/forum/viewtopic.php?t=55]Nutzungsbedingungen[/url] achten sollte.

Wer sich über andere Behandlungsansätze für psychische Störungen und Methoden mit der Problematik umzugehen informieren und austauschen möchte, ist in der Kategorie [url=http://www.adfd.org/forum/viewforum.php?f=4]Alternativen zu Antidepressiva[/url] gut aufgehoben.

Seit Mitte 2005 gibt es auch noch die Kategorie [url=http://www.adfd.org/forum/viewforum.php?f=16]Benzodiazepine absetzen[/url].
Benzodiazepine waren in gewisser Weise die Vorgänger der "modernen" Antidepressiva - nicht so sehr von der Wirkungsweise, aber vom Einsatzgebiet her. Ihr großes Abhängigkeitspotential ist mittlerweile lange bekannt, aber bis heute ist die Aufklärung darüber noch mangelhaft und eine angemessene Unterstützung beim langsamen Ausschleichen dieser Medikamente bis heute eher selten. Benzodiazepine werden auch häufig zusammen mit "modernen" Antidepressiva verschrieben, um deren zahlreiche Nebenwirkungen erträglicher zu machen.

[b]Du bist hier also richtig, wenn ...[/b]
[list]
[*]  ... Du (aus was für Gründen auch immer) dabei bist ein Antidepressivum abzusetzen und Du Dich mit anderen Betroffenen darüber austauschen willst, um Mut und Hoffnung zu bekommen diese für manche sehr schwere Zeit durchzustehen.
[*]  ... Dir ein Antidepressivum verschrieben wurde, Du aber Zweifel an der Richtigkeit dieser Verschreibung hast (weil Du z.B. nicht sicher bist, ob die Untersuchung, die zu dieser Diagnose führte, sorgfältig genug war, oder du allgemeine Zweifel an der Wirksamkeit und Sicherheit des Medikamentes hast.
[*]  ... Du aus anderen Gründen unentschlossen bist, ob Du ein Antidepressivum weiter nehmen oder absetzen sollst und Dich darüber austauschen möchtest.
[*]  ... Du erfolgreich ein Antidepressivum abgesetzt hast und jetzt anderen helfen möchtest, indem Du Deine Erfahrungen mit ihnen teilst.
[*]  ... Du den Verdacht hast, dass Du unter den Nebenwirkungen eines Antidepressivums leidest, Dein Arzt dies aber als Symptome einer psychischen Krankheit interpretiert und Dich dazu anhält, das Medikament weiter einzunehmen oder gar die Dosis steigern will.
[*]  ... die Einnahme des Antidepressivums Deine Symptome nicht bessert oder es Dir sogar schlechter geht und Du nicht weißt, ob es Sinn macht, das Medikament weiter einzunehmen.
[*]  ... Du ein Angehöriger einer Person bist, auf die einer der obengenannten Punkte zutrifft.
[*]  ... Du Arzt oder im weitesten Sinne im therapeutischen Bereich tätig bist und Dich bei einer unabhängigen Stelle über Nebenwirkungen und Abhängigkeitspotential moderner Antidepressiva informieren möchtest.[/list]

[b]Und jetzt noch wofür dieses Forum [u]nicht[/u] gedacht ist:[/b]
[list]
[*]  Um Medikamentenempfehlungen auszutauschen
[*]  Um sich über das Leben mit Antidepressiva auszutauschen - also z.B. Diskussionen darüber, wie man am besten mit den zahlreichen Nebenwirkungen "moderner" Antidepressiva klarkommt, ob man die Dosis steigern, ein zusätzliches Medikament oder ein anderes Medikament ausprobieren oder wie man am besten von einem Antidepressivum auf ein anderes umstellt.
[*]  Leuten ihre Angst zu nehmen, denen ein Antidepressivum verschrieben wurde. Wir können hier niemandem guten Gewissens zur Einnahme eines modernen Antidepressivums raten ... es sei denn er oder sie hat vorher wirklich [b]alles andere[/b] ausprobiert, um Besserung der Symptome zu erfahren (und das ist wirklich eine ganze Menge - siehe z.B: [url=http://www.adfd.org/forum/viewforum.php?f=4]Alternativen zu Antidepressiva[/url]).[/list]

Das bedeutet nicht, das wir der Meinung sind, diese Themen haben keine Daseinsberechtigung, aber der Austausch über diese Themen findet sowieso schon in den meisten anderen Foren zum Thema psychische Störungen statt und wir haben eben eine andere Ausrichtung. Wenn ihr Euch über solche Themen austauschen wollt, könnt ihr diese Foren sehr leicht leicht per Suche z.B. bei [url=http://www.google.de]Google[/url] finden.
Ein paar Suchtipps: [url=http://www.google.de/search?num=50&hl=de&biw=1262&q=depressionen+forum&btnG=Suche&meta=lr%3Dlang_de]depressionen forum[/url], [url=http://www.google.de/search?num=50&hl=de&biw=1262&q=zwangsst%C3%B6rung+forum&btnG=Suche&meta=lr%3Dlang_de]zwangsstörung forum[/url], [url=http://www.google.de/search?q=angstst%C3%B6rung+forum&sourceid=opera&num=50&ie=utf-8&oe=utf-8&lr=lang_de]angststörung forum[/url], [url=http://www.google.de/search?num=50&hl=de&biw=1262&q=paroxetin+nebenwirkungen+forum&btnG=Suche&meta=lr%3Dlang_de]paroxetin nebenwirkungen forum[/url], [url=http://www.google.de/search?num=50&hl=de&biw=1262&q=antidepressiva+nebenwirkungen+mildern+forum&btnG=Suche&meta=lr%3Dlang_de]antidepressiva nebenwirkungen mildern forum[/url].

[b]UPDATE (19.12.2005)[/b]
Dieses Forum sollte von den Teilnehmern [b]nur[/b] für den ihm angedachten und oben ausführlich erläuterten Zweck verwendet werden. In gewissen Grenzen kann natürlich auch [url=http://de.wikipedia.org/wiki/Off_topic]Off-Topic[/url] und privat diskutiert werden. Diese Off-Topic Diskussionen sollten aber [b]in jedem Fall[/b] nur in der dafür vorgesehenen Sektion (Persönlicher Austausch) geführt werden. Wir behalten uns vor, Forenteilnehmer zu bitten, beim Thema zu bleiben, falls der Off-Topic-Anteil überhand nimmt und wenn nötig auch Themen oder Nutzer zu sperren.

Linda Best und Oliver Walter